[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "nft"
  included_files = ["node_modules/@sparticuz/chromium/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
